# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190323_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='photo',
            field=models.ImageField(blank=True, default='articles/NoPic.png', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='articles/NoPic.png', upload_to='articles/'),
        ),
    ]
