# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190323_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Neigh_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Neighbourhood'),
        ),
    ]
